export const NEED_LIST_REQUEST = 'NEED_LIST_REQUEST';
export const NEED_LIST_SUCCESS = 'NEED_LIST_SUCCESS';
export const NEED_LIST_FAIL = 'NEED_LIST_FAIL';

export const NEED_DETAILS_REQUEST = 'NEED_DETAILS_REQUEST';
export const NEED_DETAILS_SUCCESS = 'NEED_DETAILS_SUCCESS';
export const NEED_DETAILS_FAIL = 'NEED_DETAILS_FAIL';
